# CONFIGURACI�N DEL SERVIDOR
server:
  port: ${PORT:8080}
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # ZONA HORARIA Y LOCALE
  jackson:
    time-zone: America/Lima
    locale: es_PE
  # PERFIL ACTIVO DE SPRING
  profiles:
    active: dev

# VARIABLES DE ENTORNO DE LA APLICACI�N
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION} # en milisegundos (ejemplo: 86400000 = 1 día)
    refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION} # en miliseg
  reniec:
    api-url: ${RENIEC_API_URL}
    api-key: ${RENIEC_API_KEY}
  sunat:
    api-url: ${SUNAT_API_URL}
    api-key: ${SUNAT_API_KEY}
  uit:
    value:
      pen: ${UIT_PEN}
  mercado-pago:
    access-token: ${MP_ACCESS_TOKEN}
    public-key: ${MP_PUBLIC_KEY}
    webhook-url: ${MP_WEBHOOK_URL}
    back-url-base: ${MP_BACK_URL_BASE}
  apisperu:
    api-url: ${APISPERU_API_URL}
    api-key: ${APISPERU_API_KEY}
    ruc-emisor: ${APISPERU_RUC_EMISOR}
    razon-social-emisor: ${APISPERU_RAZON_SOCIAL_EMISOR}
    emisor-ubigueo: "130101"
    emisor-departamento: "LA LIBERTAD"
    emisor-provincia: "TRUJILLO"
    emisor-distrito: "TRUJILLO"
    emisor-direccion: "Av. América Sur N.º 3145, Urbanización Monserrate"
  do:
    spaces:
        access-key: ${DO_SPACES_ACCESS_KEY}
        secret-key: ${DO_SPACES_SECRET_KEY}
        region: ${DO_SPACES_REGION}
        bucket-name: ${DO_SPACES_BUCKET_NAME}
        endpoint-url: ${DO_SPACES_ENDPOINT_URL}
---
# CONFIGURACI�N DE BASE DE DATOS (Perfil de Producci�n - Heroku)
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # No crear/modificar tablas en prod

---
# CONFIGURACI�N DE BASE DE DATOS (Perfil de Desarrollo - H2)
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:prestamosdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Crear/actualizar tablas en dev
  h2:
    console:
      enabled: true
